### ISSUE TITLE
Validation of an identity token by third-party private feed host

### ISSUE THREAD

**Issue by inorganik** [podpass/spec#10]
> If the identity payload included Compatible Feeds, the listener is presented with the option to quick-connect their identity to the compatible feeds. The Adopt Flow is automatically completed for each feed the listener chooses.

For the "Patreon use-case", how is the Identity Token validated by the third party (Patreon), since it was created by a separate host? Does the host have to expose a special auth endpoint for third-party hosts to validate tokens?

**Comment by cqr** [comment]
There are a couple of things you could be talking about here: the portion you quoted allows any arbitrary URL to receive the token by defining an adopt URL, so it could definitely be on Patreon.com, if that's the URL in the public feed.

For authenticated requests to the feed, if the public feed is unable to support it, you can send a new feed URL in the id payload, so that the user agent will make future requests to the new (in this case, likely Patreon.com hosted) feed url.

**Comment by inorganik** [comment]
I'm just trying to understand how the patreon use case works, but it's not quite clear to me from the spec.  Let's say I host my podcast on Simplecast, but I want to drive users to a private Patreon feed. 

So in my simplecast feed (assuming it's supported by simplecast) do I just include a podpass tag that points to Patreon, so Patreon can do the identity flow (if supported)?

```xml
<pass:id href="https://patreon.com/podpass/identify" />
```
Then Patreon identity window sends payload with `compatible` holding the private feed url via app communication api?

**Comment by cqr** [comment]
Everything up until compatible is correct - it would send back the new feed URL as feedURL. Compatible is a list of other compatible public feeds which can be authenticated by the same system. In the patreon case, this would be a list of other public feeds which are connected to patreon campaigns you support, for instance.

**Comment by inorganik** [comment]
Cool, thanks!
